# Generated by Django 3.1.4 on 2020-12-31 19:20

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_image_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(null=True, upload_to='image_folder', validators=[main.validators.validate_extension]),
        ),
    ]
