# Generated by Django 3.1.4 on 2021-01-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210101_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='search',
            field=models.BooleanField(default=False),
        ),
    ]
