# Generated by Django 3.1.4 on 2021-01-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_image_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='search',
        ),
    ]
